version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - '4200:4200'

networks:
  my-network:
    external: true
