version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      docker_mynetwork:
          ipv4_address: 172.20.0.4
    ports:
      - '4200:4200'

networks:
  docker_mynetwork:
    external: true
